### ISSUE TITLE
Can't debug plain text data within eyaml files

### ISSUE THREAD

**Issue by derekedmond** [TomPoulton/hiera-eyaml#221]
Hi, 

We keep all of our Hiera data in *.eyaml files. Most keys are encrypted, but some are not. I would like to use the hiera command line tool to debug plain text values inside our *.eyaml files.

```
hiera.yaml:
---
:backends:
  - eyaml

:hierarchy:
  - common

:eyaml:
  :datadir: /etc/puppetlabs/code/hiera/data # for use with Puppet v4 Puppet masters
  :gpg_gnupghome: /home/puppet/.gnupg
```
```
common.eyaml:
---
dhcpd::ensure:       'running'
```

When I want to test this on the command line, I get this error: 

```
$ hiera -d -c /etc/puppetlabs/code/hiera.yaml 'dhcpd::ensure' 
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/hiera/config.rb:78:in `rescue in block in load_backends': Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend (RuntimeError)
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/hiera/config.rb:75:in `block in load_backends'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/hiera/config.rb:74:in `each'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/hiera/config.rb:74:in `load_backends'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/hiera.rb:51:in `initialize'
        from /opt/puppetlabs/bin/hiera:232:in `new'
        from /opt/puppetlabs/bin/hiera:232:in `<main>'
```

As a workaround, I know I could rename all the files to *.yaml and add a yaml backend, but I'm trying to avoid that. I just don't know if I'm trying to do something that is impossible. Any ideas?

**Comment by xyr115** [comment]
Is there any movement on this? I'm getting the same error in Puppet 4
